name: Build and Release Lynchy Adventure

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix git safe directory
        run: git config --global --add safe.directory $GITHUB_WORKSPACE

      - name: Extract version
        id: get_version
        shell: bash
        run: |
          msg=$(git log -1 --pretty=%B)
          if [[ $msg =~ [Vv](ersion)?[^0-9]*([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            echo "version=${BASH_REMATCH[2]}" >> $GITHUB_OUTPUT
          fi

      - name: Build
        run: make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            *.3dsx

  release:
    needs: build
    if: needs.build.outputs.version != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.build.outputs.version }}
          name: Version ${{ needs.build.outputs.version }}
          files: |
            *.3dsx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}